POST http://127.0.0.1:8000/api/login
Content-Type: application/json

{"username":"Daniel", "password":"Pass1234!"}

###

POST http://127.0.0.1:8000/api/signup
Content-Type: application/json

{"username":"Daniel", "password":"Pass1234!", "email":"modaniel167@gmail.com"}


###
GET http://127.0.0.1:8000/api/expenses
Authorization: Token e0637ce7ca3516ec4434d059831d45747c4702e8

###
POST http://127.0.0.1:8000/api/expense/create
Content-Type: application/json

{"name":"newexpesnce",
"amount_spent":50,
"note":"new",
"category_data":{"title":"help"},
"date_added":"2025-11-21",
"user":1}


###
GET http://127.0.0.1:8000/api/categories
Content-Type: application/json

###
POST http://127.0.0.1:8000/api/category/create
Content-Type: application/json

{"title":"one"}
