# Generated by Django 5.2.8 on 2025-11-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_expenses_amount_spent_expenses_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='amount_spent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
